### ISSUE TITLE
Can you add env file example?

### ISSUE THREAD

**Issue by ranmax123** [Farzad-R/Advanced-RAG-Series#2]

**Comment by Farzad-R** [comment]
Hi ranmax123,
here is an example of the env file that I used for this repository.

OPENAI_API_TYPE=azure
OPENAI_API_VERSION=2023-07-01-preview
OPENAI_API_KEY=<KEY>
OPENAI_API_BASE=<Azure OpenAI URL>

For each project check the config/config.yml and make sure the set the correct LLM name and Embedding model name (if needed). The names should match the model names that you have deployed on Azure. Please let me know if this could help you resolve the issue.
