### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by ranmax123** [Farzad-R/Advanced-RAG-Series#3]
"AuthenticationError(\"Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com) , or have expired.'}

I'm getting above error when running the solution. I have already added the env file content
OPENAI_API_KEY=
OPENAI_API_BASE=
OPENAI_API_VERSION=2024-02-01
gpt_deployment_name=gpt35Turbo
embed_deployment_name=embeddingada

**Comment by Farzad-R** [comment]
Hi ranmax123,
here is an example of the env file that I used for this repository.

OPENAI_API_TYPE=azure
OPENAI_API_VERSION=2023-07-01-preview
OPENAI_API_KEY=<KEY>
OPENAI_API_BASE=<Azure OpenAI URL>

For each project check the config/config.yml and make sure the set the correct LLM name, `gpt35Turbo` in your case,  and Embedding model name. `embeddingada` in your case. The names should match the model names that you have deployed on Azure. Please let me know if this could help you resolve the issue.
