### ISSUE TITLE
ACCESS TO OPENAI ISSUE FROM CODE

### ISSUE THREAD

**Issue by naggu0709** [Farzad-R/Advanced-RAG-Series#5]
[github_.docx](https://github.com/user-attachments/files/17039256/github_.docx)

**Comment by Farzad-R** [comment]
Hi naggu0709,

Would you please copy and paste the error directly in here? you can wrap it up in ``` to look better if you want. Example:

```
test 123
```

**Comment by naggu0709** [comment]
{
	"name": "NotFoundError",
	"message": "Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}",
	"stack": "---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
Cell In[8], line 16
      3 messages = [
      4     {\"role\": \"system\", \"content\": str(
      5         \"You are a helpful assistant\"
      6     )},
      7     {\"role\": \"user\", \"content\": str(\"hello\")}
      8 ]
     10 client = AzureOpenAI(
     11     api_version=os.getenv(\"OPENAI_API_VERSION\"),
     12     azure_endpoint=os.getenv(\"OPENAI_API_BASE\"),
     13     api_key=os.getenv(\"OPENAI_API_KEY\"),
     14 )
---> 16 response = client.chat.completions.create(
     17     model=os.getenv(\"gpt_deployment_name\"),
     18     messages=messages
     19 )
     21 print(response.choices[0].message.content)

File c:\\Users\\Nagu\\anaconda3\\Lib\\site-packages\\openai\\_utils\\_utils.py:274, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    272             msg = f\"Missing required argument: {quote(missing[0])}\"
    273     raise TypeError(msg)
--> 274 return func(*args, **kwargs)

File c:\\Users\\Nagu\\anaconda3\\Lib\\site-packages\\openai\\resources\\chat\\completions.py:704, in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_completion_tokens, max_tokens, n, parallel_tool_calls, presence_penalty, response_format, seed, service_tier, stop, stream, stream_options, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
    668 @required_args([\"messages\", \"model\"], [\"messages\", \"model\", \"stream\"])
    669 def create(
    670     self,
   (...)
    701     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    702 ) -> ChatCompletion | Stream[ChatCompletionChunk]:
    703     validate_response_format(response_format)
--> 704     return self._post(
    705         \"/chat/completions\",
    706         body=maybe_transform(
    707             {
    708                 \"messages\": messages,
    709                 \"model\": model,
    710                 \"frequency_penalty\": frequency_penalty,
    711                 \"function_call\": function_call,
    712                 \"functions\": functions,
    713                 \"logit_bias\": logit_bias,
    714                 \"logprobs\": logprobs,
    715                 \"max_completion_tokens\": max_completion_tokens,
    716                 \"max_tokens\": max_tokens,
    717                 \"n\": n,
    718                 \"parallel_tool_calls\": parallel_tool_calls,
    719                 \"presence_penalty\": presence_penalty,
    720                 \"response_format\": response_format,
    721                 \"seed\": seed,
    722                 \"service_tier\": service_tier,
    723                 \"stop\": stop,
    724                 \"stream\": stream,
    725                 \"stream_options\": stream_options,
    726                 \"temperature\": temperature,
    727                 \"tool_choice\": tool_choice,
    728                 \"tools\": tools,
    729                 \"top_logprobs\": top_logprobs,
    730                 \"top_p\": top_p,
    731                 \"user\": user,
    732             },
    733             completion_create_params.CompletionCreateParams,
    734         ),
    735         options=make_request_options(
    736             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    737         ),
    738         cast_to=ChatCompletion,
    739         stream=stream or False,
    740         stream_cls=Stream[ChatCompletionChunk],
    741     )

File c:\\Users\\Nagu\\anaconda3\\Lib\\site-packages\\openai\\_base_client.py:1268, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1254 def post(
   1255     self,
   1256     path: str,
   (...)
   1263     stream_cls: type[_StreamT] | None = None,
   1264 ) -> ResponseT | _StreamT:
   1265     opts = FinalRequestOptions.construct(
   1266         method=\"post\", url=path, json_data=body, files=to_httpx_files(files), **options
   1267     )
-> 1268     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File c:\\Users\\Nagu\\anaconda3\\Lib\\site-packages\\openai\\_base_client.py:945, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    942 else:
    943     retries_taken = 0
--> 945 return self._request(
    946     cast_to=cast_to,
    947     options=options,
    948     stream=stream,
    949     stream_cls=stream_cls,
    950     retries_taken=retries_taken,
    951 )

File c:\\Users\\Nagu\\anaconda3\\Lib\\site-packages\\openai\\_base_client.py:1049, in SyncAPIClient._request(self, cast_to, options, retries_taken, stream, stream_cls)
   1046         err.response.read()
   1048     log.debug(\"Re-raising status error\")
-> 1049     raise self._make_status_error_from_response(err.response) from None
   1051 return self._process_response(
   1052     cast_to=cast_to,
   1053     options=options,
   (...)
   1057     retries_taken=retries_taken,
   1058 )

NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}"
}

**Comment by Farzad-R** [comment]
The error indicates you don't have access to the OpenAI model being used, so the connection couldn’t be established. The project uses OpenAI through Azure, but you can modify the code to use OpenAI models directly, without needing Azure. My suggestion is to first make a successful API call with the OpenAI model. Then, test the project by ensuring the models are called in the same way as that successful call.
