### ISSUE TITLE
travel.sqlite missing?

### ISSUE THREAD

**Issue by jkey67** [Farzad-R/Advanced-RAG-Series#6]
I cloned your project and it did contain this db, but it was indeed empty (no tables)? Looked for it here now, and now it does not seem to be here at all anymore..

**Comment by jkey67** [comment]
Found it. Never mind: https://www.kaggle.com/code/mpwolke/airlines-sqlite

**Comment by Farzad-R** [comment]
I noticed the URL was wrong in the readme file. Thanks for the notice. I've now corrected it.
